package com.lanou.tong.fun.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECTION".
 */
public class Collection {

    private Long id;
    private String title;
    private String content;
    private String docId;
    private String src;

    public Collection() {
    }

    public Collection(Long id) {
        this.id = id;
    }

    public Collection(Long id, String title, String content, String docId, String src) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.docId = docId;
        this.src = src;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDocId() {
        return docId;
    }

    public void setDocId(String docId) {
        this.docId = docId;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

}
